roomie/urls.py
from django.urls import include, path

from scheduler.admin import admin_site

urlpatterns = [
    path("", include("scheduler.urls")),
    path("admin/", admin_site.urls),
]

scheduler/urls.py
# Copyright (c) 2021 Jonathan Vice

from django.urls import path

from . import views

app_name = "scheduler"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("add-room", views.add_room, name="add_room"),
    path("add-event", views.add_event, name="add_event"),
]

scheduler/models.py
# Copyright (c) 2021 Jonathan Vice

from django.db import models


class Room(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self) -> str:
        return self.name


class Event(models.Model):
    name = models.CharField(max_length=30)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    # auto_now_add uses date at time of record creation. Cannot be modified.
    request_date = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.name

scheduler/forms.py
# Copyright (c) 2021 Jonathan Vice

from django import forms

from .models import Room


class AddRoomForm(forms.Form):
    room_name = forms.CharField(label="Room Name")


class AddEventForm(forms.Form):
    room = forms.ModelChoiceField(queryset=Room.objects.all())
    event_name = forms.CharField(label="Event Name")

scheduler/views.py
# Copyright (c) 2021 Jonathan Vice

from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils import dateparse, timezone
from django.views import generic

from .forms import AddRoomForm, AddEventForm
from .models import Event, Room


class IndexView(generic.TemplateView):
    template_name = "scheduler/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Add to page context here
        context["data"] = {
            "rooms": Room.objects.all(),
            "current_events": self.get_current_events(),
            "upcoming_events": self.get_upcoming_events(),
            "add_room_form": AddRoomForm(),
            "add_event_form": AddEventForm(),
            # TODO: "edit_event_form": EventForm(instance=?) check docs
        }

        return context

    def get_current_events(self):
        """Return events that are taking place now."""
        events = Event.objects.filter(start_time__lte=timezone.now()).filter(
            end_time__gte=timezone.now()
        )

        return events

    def get_upcoming_events(self):
        """Return events that will take place in the future."""
        # TODO: Add option to select how far to look for upcoming events
        events = Event.objects.filter(start_time__gte=timezone.now())

        return events


def add_room(request):
    Room.objects.create(name=request.POST["room_name"])

    return HttpResponseRedirect(reverse("scheduler:index"))


def add_event(request):
    room = get_object_or_404(Room, pk=request.POST["room"])
    start_date = (
        f"{request.POST['event-start-date']} {request.POST['event-start-time']}"
    )
    end_date = f"{request.POST['event-end-date']} {request.POST['event-end-time']}"

    start_date = dateparse.parse_datetime(start_date)
    end_date = dateparse.parse_datetime(end_date)

    Event.objects.create(
        name=request.POST["event_name"],
        room=room,
        start_time=start_date,
        end_time=end_date,
        request_date=timezone.now(),
    )

    return HttpResponseRedirect(reverse("scheduler:index"))

scheduler/templates/scheduler/index.html
<!-- Copyright (c) 2021 Jonathan Vice -->

{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Roomie</title>
    <link rel="stylesheet" href="{% static 'scheduler/style.css' %}">
</head>
<body>
    <div class="index-rooms-section">
        <h2>Rooms</h2>
        <ul>
        {% for room in data.rooms %}
            <li>{{ room }}</li>
        {% endfor %}
        </ul>
    </div>
    
    <div class="index-events-container">
        <h2>Ongoing Events</h2>
        <ul>
        {% for event in data.current_events %}
            <li>{{ event }} in {{ event.room|lower }} from {{ event.start_time|date:"N jS H:i" }} to {{ event.end_time|date:"N jS H:i" }}</li>
        {% empty %}
            <li>There are no ongoing events</li>
        {% endfor %}
        </ul>
    </div><br>
    
    <div class="index-events-container">
        <h2>Upcoming Events</h2>
        <ul>
        {% for event in data.upcoming_events %}
            <li>{{ event }} in {{ event.room|lower }} from {{ event.start_time|date:"N jS H:i" }} to {{ event.end_time|date:"N jS H:i" }}</li>
        {% empty %}
            <li>There are no upcoming events</li>
        {% endfor %}
        </ul>
    </div>

    <div class="index-controls-section">
        <button onclick="displayModal('add-room-modal')">Add room</button>
        <button onclick="displayModal('add-event-modal')">Add event</button>
    </div>

    <!-- Add room modal form -->
    <div id="add-room-modal" class="modal">
        <div class="modal-content">
            <span id="add-room-modal-close" class="close">&times;</span>
            <form action="{% url 'scheduler:add_room' %}" method="post">
                {% csrf_token %}
                <h3>Add Room</h3>
                {{ data.add_room_form.as_p }}
                <input type="submit" value="Add" class="btn">
            </form>
        </div>
    </div>

    <!-- Add event modal form -->
    <div id="add-event-modal" class="modal">
        <div class="modal-content">
            <span id="add-event-modal-close" class="close">&times;</span>
            <form action="{% url 'scheduler:add_event' %}" method="post">
                {% csrf_token %}
                <h3>Add Event</h3>
                {{ data.add_event_form.as_p }}

                <p><label for="event-start-date">Start Date & Time</label><br>
                <input type="date" name="event-start-date" id="event-start-date" required>
                <input type="time" name="event-start-time" id="event-start-time" required></p>

                <p><label for="event-end-date">End Date & Time</label><br>
                <input type="date" name="event-end-date" id="event-end-date" required>
                <input type="time" name="event-end-time" id="event-end-time" required></p>

                <input type="submit" value="Add" class="btn">
            </form>
        </div>
    </div>

    <!-- Include js script -->
    <script src="{% static 'scheduler/script.js' %}"></script>
</body>
</html>